### ISSUE TITLE
rpki-validator seems to use a hardcoded path conf/log4j.xml

### ISSUE THREAD

**Issue by chaica** [RIPE-NCC/rpki-validator#1]
Hi,

I'm trying to realize a package with rpki-validator. In order to realize a good integration of this app on my system, I tried to modify CONF_DIR in order to be able to move the ./conf into /etc/rpki-validator/conf

But when I start rpki-validator.sh, I only get the following message:
# /etc/init.d/rpki-validator.sh start

[ info ] Starting rpki-validator...
[ info ] writing logs under log directory
[ info ] Web user interface is available on port 8080
[ info ] Routers can connect on port 8282
[ info ] Writing PID 22630 to /var/run/rpki-validator.pid
 Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Configuration file 'conf/log4j.xml' was not found.
    at scala.Predef$.require(Predef.scala:233)
    at net.ripe.rpki.validator.config.Main$.configureLogging(Main.scala:86)
    at net.ripe.rpki.validator.config.Main$.main(Main.scala:75)
    at net.ripe.rpki.validator.config.Main.main(Main.scala)

I just discovered the source code on Github and read that conf/log4j.xml seems hardcoded directly in the source code. Would it be possible to find a way in order it is not hardcoded ? Maybe by putting a path into the .sh or in a conf file ? Or maybe I'm missing something?

Thanks,
Carl Chenet

**Comment by timbru** [comment]
We had no feedback otherwise, so assume this addressed the issue.
