### ISSUE TITLE
SQL error when forcing updates of the Trust Anchors

### ISSUE THREAD

**Issue by galphanet** [RIPE-NCC/rpki-validator#22]
- Debian 8 Jessie 64 bits
  * rpki-validator version 2.23 (clean install)
- java version "1.7.0_111"
  OpenJDK Runtime Environment (IcedTea 2.6.7) (7u111-2.6.7-1~deb8u1)
  OpenJDK 64-Bit Server VM (build 24.111-b01, mixed mode)

Steps to reproduce:
1. Start the validator application
2. Connect to the web interface to the URL /trust-anchors
4. Click the "Update all" button
5. Error appear

[ERROR] [09/30/2016 19:14:45.969] [default-akka.actor.default-dispatcher-3] [TaskInvocation] Error executing statement at line 5: CALL DROP_TABLE_IF_EXISTS('RETRIEVED_OBJECTS')
com.googlecode.flyway.core.command.FlywaySqlScriptException: Error executing statement at line 5: CALL DROP_TABLE_IF_EXISTS('RETRIEVED_OBJECTS')
    at com.googlecode.flyway.core.dbsupport.SqlScript.execute(SqlScript.java:92)
    at com.googlecode.flyway.core.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:72)
    at com.googlecode.flyway.core.command.DbMigrate$2.doInTransaction(DbMigrate.java:243)
    at com.googlecode.flyway.core.command.DbMigrate$2.doInTransaction(DbMigrate.java:241)
    at com.googlecode.flyway.core.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
    at com.googlecode.flyway.core.command.DbMigrate.applyMigration(DbMigrate.java:241)
    at com.googlecode.flyway.core.command.DbMigrate.access$700(DbMigrate.java:44)
    at com.googlecode.flyway.core.command.DbMigrate$1.doInTransaction(DbMigrate.java:186)
    at com.googlecode.flyway.core.command.DbMigrate$1.doInTransaction(DbMigrate.java:135)
    at com.googlecode.flyway.core.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
    at com.googlecode.flyway.core.command.DbMigrate.migrate(DbMigrate.java:135)
    at com.googlecode.flyway.core.Flyway$1.execute(Flyway.java:872)
    at com.googlecode.flyway.core.Flyway$1.execute(Flyway.java:819)
    at com.googlecode.flyway.core.Flyway.execute(Flyway.java:1200)
    at com.googlecode.flyway.core.Flyway.migrate(Flyway.java:819)

**Comment by agallo** [comment]
Same results on Redhat with the following config:
* Red Hat Enterprise Linux Server release 6.7 (Santiago)
  * Linux rpkiprdapp2 2.6.32-573.18.1.el6.x86_64 #1 SMP Tue Feb 9 02:33:56 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
* java version "1.7.0_95"
  * OpenJDK Runtime Environment (rhel-2.6.4.0.0.1.el6_7-x86_64 u95-b00)
  * OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
* rpki-validator-app-2.23

**Comment by AlexanderBand** [comment]
Hi Andrew,
Do you have a chance to try it with Java 8? I had the same problem last week and after switching to the latest Java, the error went away. I'll have a look if we need to rebuild the package to support Java 7 properly. Currently I'm running this on MacOS Sierra:

$ java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)

Cheers,
Alex

**Comment by agallo** [comment]
That did the trick.  I tested it on a different OS (Debian 8.6), but with openjdk-7-jre I got the same error, but it works fine with openjdk-8-jre:
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2~bpo8+1-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)


TALs are updating, prefixes are validating.

Thank you!

**Comment by agallo** [comment]
BTW, we have no specific need for Java 7, so for us, additional effort to support Java 7 isn't something we would be asking for.

Thanks.

**Comment by AlexanderBand** [comment]
ok good to know. Nonetheless, I'll ask the engineers how much effort it would be to also support Java 7.

**Comment by timbru** [comment]
There is an issue with java 7 and one of the libraries that the code depends on. In addition to this Java 7 has been unsupported by oracle since july 2015, and although OpenJDK 7 still sees some maintenance, new versions are available.

So, we do not plan to support java 7 going forward.

**Comment by timbru** [comment]
Closing issue, won't support Java 7 as mentioned in last comment
