### ISSUE TITLE
Crashes after a few minutes

### ISSUE THREAD

**Issue by bortzmeyer** [RIPE-NCC/rpki-validator#24]
```
[ERROR] [03/14/2017 16:18:08.349] [default-akka.actor.default-dispatcher-6] [ActorSystem(default)] Uncaught error from thread [default-akka.actor.default-dispatcher-6] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.ExceptionInInitializerError
	at scala.collection.parallel.ParIterableLike$class.$init$(ParIterableLike.scala:166)
	at scala.collection.parallel.immutable.ParVector.<init>(ParVector.scala:43)
	at scala.collection.immutable.Vector.par(Vector.scala:88)
	at scala.collection.immutable.Vector.par(Vector.scala:67)
	at net.ripe.rpki.validator.bgp.preview.BgpRisDump$$anonfun$1.apply(BgpRisDump.scala:50)
	at net.ripe.rpki.validator.bgp.preview.BgpRisDump$$anonfun$1.apply(BgpRisDump.scala:52)
	at net.ripe.rpki.validator.lib.DateAndTime$.timed(DateAndTime.scala:70)
	at net.ripe.rpki.validator.bgp.preview.BgpRisDump$.toAnnouncedRoutes(BgpRisDump.scala:49)
	at net.ripe.rpki.validator.bgp.preview.BgpRisDumpDownloader$$anon$1.handleResponse(BgpRisDumpDownloader.scala:93)
	at net.ripe.rpki.validator.bgp.preview.BgpRisDumpDownloader$$anon$1.handleResponse(BgpRisDumpDownloader.scala:81)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:218)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:136)
	at net.ripe.rpki.validator.bgp.preview.BgpRisDumpDownloader$$anonfun$download$1$$anonfun$apply$2.apply(BgpRisDumpDownloader.scala:65)
	at net.ripe.rpki.validator.bgp.preview.BgpRisDumpDownloader$$anonfun$download$1$$anonfun$apply$2.apply(BgpRisDumpDownloader.scala:65)
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:173)
	at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:171)
	at scala.concurrent.package$.blocking(package.scala:50)
	at net.ripe.rpki.validator.bgp.preview.BgpRisDumpDownloader$$anonfun$download$1.apply(BgpRisDumpDownloader.scala:65)
	at net.ripe.rpki.validator.bgp.preview.BgpRisDumpDownloader$$anonfun$download$1.apply(BgpRisDumpDownloader.scala:58)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:137)
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NumberFormatException: Not a version: 9
	at scala.util.PropertiesTrait$class.parts$1(Properties.scala:176)
	at scala.util.PropertiesTrait$class.isJavaAtLeast(Properties.scala:180)
	at scala.util.Properties$.isJavaAtLeast(Properties.scala:16)
	at scala.collection.parallel.package$.getTaskSupport(package.scala:45)
	at scala.collection.parallel.package$.<init>(package.scala:48)
	at scala.collection.parallel.package$.<clinit>(package.scala)
	... 29 more
```

RPKI validator 2.23

```
% java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)
```

**Comment by bortzmeyer** [comment]
Downgrading :-( to version 8 fixed the problem.

```
% $JAVA_HOME/bin/java -version 
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**Comment by timbru** [comment]
Until now we have been quite restrictive in which java version is supported, as it says in the README.txt we have tested and support Oracle JDK 8. But it seems that the java version check in the start-up script  is somewhat naive about the expected format.

We are planning to do a lot of work on the validator starting mid May - immediately after the RIPE Meeting. We will investigate whether we can properly support other JDK versions. I do like the idea of supporting OpenJDK in particular, but can't promise anything yet. We can only 'officially' support it if we are confident that our code *and* the libraries we depend on are stable with those versions.
